name: openfe
channels:
  - jaimergp/label/unsupported-cudatoolkit-shim
  - conda-forge
  - openeye
dependencies:
  - numpy
  - networkx
  - rdkit
  - pip
  - pytest
  - pytest-xdist
  - pytest-cov
  - pydantic
  - coverage
  - openff-toolkit
  - openff-units>=0.1.6
  - openmmforcefields
  - click
  - openeye-toolkits
  - typing-extensions
  # temporarily disable lomap to use main instead
  # - lomap2
  - openmmtools
  - pip:
    - git+https://github.com/OpenFreeEnergy/gufe@main
    - git+https://github.com/OpenFreeEnergy/Lomap@main
    - plugcli
