name: "CI"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    # At 00:00 on Monday and Thursday.
    - cron: "0 7 * * 1,4"

concurrency:
  group: "${{ github.ref }}-${{ github.head_ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  tests:
    runs-on: ${{ matrix.OS }}-latest
    name: "tests"
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
        os: ['ubuntu', 'windows', 'macos']

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
            auto-update-conda: true
            use-mamba: true
            python-version: ${{ matrix.python-version }}
            miniforge-variant: Mambaforge
            environment-file: environment.yml
            activate-environment: openfe

      - name: "Versions"
        run: conda list

      - name: "Install"
        run: python setup.py develop --no-deps

      - name: "Environment Information"
        run: |
          mamba info -a
          mamba list

      - name: "Run tests"
        run: |
          pytest -n 2 -v --cov=openfe --cov-report=xml openfe/tests/

      - name: codecov
        uses: codecov/codecov-action@v2
        with:
          file: coverage.xml
          fail_ci_if_error: True
          verbose: True
